openapi: 3.0.0
info:
  description: Checkout API Designed By IDEALO
  version: "0.0.1.RELEASE"
  title: Checkout API
  contact:
    email: aqibbutt3078@gmail.com
paths:
  /checkout/:
    post:
      tags:
        - Checkout Requests
      summary: Call for checking out SKU.
      operationId: checkout
      description: API for support to checkout all SKU.
      responses:
        '200':
          description: Items checkout successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CheckoutResponse'
        '400':
          description: Invalid checkout, Bad Request.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseError'
        '403':
          description: Items not exists for checkout.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseError'
        '417':
          description: Expectation given in the request's Expect header could not be met.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseError'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CheckoutRequest'
components:
  schemas:
    CheckoutRequest:
      type: object
      properties:
        skuList:
          type: array
          items:
            type: string
    CheckoutResponse:
      required:
        - total
        - productShortResponse
      type: object
      properties:
        total:
          type: integer
          format: int64
        productShortResponse:
          type: array
          items:
            $ref: '#/components/schemas/ProductShortResponse'
    ProductShortResponse:
      type: object
      properties:
        sku:
          type: string
        productId:
          type: string
        quantity:
          type: integer
          format: int32
        unitPrice:
          type: integer
          format: int32
        detailedMessage:
          type: string
    ProductDetailResponse:
      type: object
      properties:
        sku:
          type: string
        productId:
          type: string
        productName:
          type: string
        madeIn:
          type: string
        brand:
          type: string
        unitPrice:
          type: integer
          format: int32
        quantity:
          type: integer
          format: int32
        supplierName:
          type: string
        insertedAt:
          type: string
        updatedAt:
          type: string
    GetProductBySkuResponse:
      type: object
      properties:
        productShortResponseList:
          type: array
          items:
            $ref: '#/components/schemas/ProductShortResponse'
    ResponseError:
      type: object
      properties:
        errorCode:
          type: integer
        errorMessage:
          type: string
        detailedMessage:
          type: string
        exceptionName:
          type: string
        createdAt:
          type: string