openapi: 3.0.0
info:
  description: Checkout API Designed By IDEALO
  version: "0.0.1.RELEASE"
  title: Checkout API
  contact:
    email: aqibbutt3078@gmail.com
paths:
  /checkout/:
    post:
      tags:
        - Checkout Requests
      summary: Call for checking out SKU.
      operationId: checkout
      description: API for support to checkout all SKU.
      responses:
        '200':
          description: Items checkout successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RuleResponse'
        '400':
          description: Invalid checkout, Bad Request.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseError'
        '403':
          description: Items not exists for checkout.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseError'
        '417':
          description: Expectation given in the request's Expect header could not be met.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseError'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CheckoutRequest'
components:
  schemas:
    CheckoutRequest:
      type: object
      properties:
        checkoutInfo:
          type: array
          items:
            $ref: '#/components/schemas/CheckoutInfo'
    CheckoutInfo:
      type: object
      properties:
        sku:
          type: string
        checkoutQuantity:
          type: integer
          format: int64
    RuleResponse:
      type: object
      properties:
        total:
          type: integer
          format: int64
        ruleInfoResponse:
          type: array
          items:
            $ref: '#/components/schemas/RuleInfoResponse'
    RuleInfoResponse:
      type: object
      properties:
        sku:
          type: string
        checkoutQuantity:
          type: integer
          format: int64
        unitPrice:
          type: integer
          format: int64
        shipping:
          type: integer
          format: int64
        specialPrice:
          type: integer
          format: int64
        detailedMessage:
          type: string
    RuleRequest:
      type: object
      properties:
        ruleInfoRequest:
          type: array
          items:
            $ref: '#/components/schemas/RuleInfoRequest'
    RuleInfoRequest:
      type: object
      properties:
        sku:
          type: string
        unitPrice:
          type: integer
          format: int64
        shipping:
          type: integer
          format: int64
        checkoutQuantity:
          type: integer
          format: int64
    GetProductBySkuResponse:
      type: object
      properties:
        productShortResponseList:
          type: array
          items:
            $ref: '#/components/schemas/ProductShortResponse'
    ProductShortResponse:
      type: object
      properties:
        sku:
          type: string
        productId:
          type: string
        quantity:
          type: integer
          format: int64
        unitPrice:
          type: integer
          format: int64
        shipping:
          type: integer
          format: int64
        detailedMessage:
          type: string
    ResponseError:
      type: object
      properties:
        errorCode:
          type: integer
        errorMessage:
          type: string
        detailedMessage:
          type: string
        exceptionName:
          type: string
        createdAt:
          type: string