openapi: 3.0.0
info:
  description: Product API Designed By IDEALO
  version: "0.0.1.RELEASE"
  title: Product API
  contact:
    email: aqibbutt3078@gmail.com
paths:
  /product/:
    post:
      tags:
        - Product Requests
      summary: Call for inserting a new product.
      operationId: addProduct
      description: API for support to add a new product.
      responses:
        '200':
          description: Item inserted successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AddProductResponse'
        '400':
          description: Invalid insert, Bad Request.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseError'
        '407':
          description: duplicate product, Cannot insert.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseError'
        '417':
          description: Expectation given in the request's Expect header could not be met.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseError'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProductRequest'
components:
  schemas:
    AddProductResponse:
      properties:
        sku:
          type: string
        productId:
          type: string
        productName:
          type: string
        detailMessage:
          type: string
    ProductRequest:
      required:
        - sku
        - productId
        - productName
        - unitPrice
        - quantity
      type: object
      properties:
        sku:
          type: string
        productId:
          type: string
        productName:
          type: string
        madeIn:
          type: string
        brand:
          type: string
        unitPrice:
          type: integer
          format: int32
        quantity:
          type: integer
          format: int32
        supplierName:
          type: string
        insertedAt:
          type: string
        updatedAt:
          type: string
    ProductShortResponse:
      type: object
      properties:
        sku:
          type: string
        productId:
          type: string
        quantity:
          type: integer
          format: int32
        unitPrice:
          type: integer
          format: int32
        detailedMessage:
          type: string
    ProductDetailResponse:
      type: object
      properties:
        sku:
          type: string
        productId:
          type: string
        productName:
          type: string
        madeIn:
          type: string
        brand:
          type: string
        unitPrice:
          type: integer
          format: int32
        quantity:
          type: integer
          format: int32
        supplierName:
          type: string
        insertedAt:
          type: string
        updatedAt:
          type: string
    ResponseError:
      type: object
      properties:
        errorCode:
          type: integer
        errorMessage:
          type: string
        detailedMessage:
          type: string
        exceptionName:
          type: string
        createdAt:
          type: string